### PR TITLE
Updating the kafka async defaults.

### PR DESCRIPTION
**Pull request by jpmedforth**
Simply changing the defaults which were set to 0.

### CODE REVIEW

**Comment by dim** [comment]
Pls bump .version too

**Comment by dim** [comment]
Can you pls run tests/rubocop, bundle versions have not been updated

**Comment by jpmedforth** [comment]
AH I see. I was having trouble getting test to run locally but I see the trick is to run the testdata compose.

**Comment by dim** [comment]
Waiting for Travis ...

**Comment by dim** [comment]
Pls merge when successful

**Pull request merged**
